### ISSUE TITLE
Character sequence `&.` can break LESS editor.

### ISSUE THREAD

**Issue by madprgmr** [LightTable/LightTable#1263]
The LESS editor (not sure what part) cannot handle `&.` in some situations.

Entering it into an active LESS document (or loading a LESS document containing it) causes the editor tab to stop responding to text entry, although keyboard shortcuts (like `CTRL+s` do work). `CTRL+z` undoes the change and restores functionality.

I cannot seem to find a specific set of circumstances that cause it, so a file that exhibits this behavior is as follows:

``` less
// &. // No issues when put here.

@import url(http://fonts.googleapis.com/css?family=Cardo:400,400italic);
@import url(http://fonts.googleapis.com/css?family=Quicksand);
@import url(http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css);

// &. // No issues when put here.

.serif() {
  // &. // Breaks when put here.
  font-family: 'Cardo', serif;
  // &. // No issues when put here.
}

.sansSerif() {
  // &. // Breaks when put here.
  font-family: 'Quicksand', sans-serif;
  // &. // No issues when put here.
}

// &. // No issues when put here.

body {
  // &. // Breaks when put here.
  .sansSerif;
  padding: 0;
  margin: 0;

  // &. // Breaks when put here.

  h1, h2, h3, h4, h5, h6 {
    // &. // Breaks when put here.
    .serif;
    // &. // Breaks when put here.
  }

  // &. // Breaks when put here.
}

// &. // No issues when put here.
```

I suspect this is related to #1062, due to the stack trace being quite similar.

Error from console is as follows:

```
Uncaught TypeError: Cannot call method 'match' of undefined
    less.js [73]               tokenBase
    less.js [294]              token
    codemirror.js [4399]       runMode
    codemirror.js [4424]       highlightLine
    codemirror.js [920]        anonymous
    codemirror.js [4793]       window.CodeMirror.LeafChunk.iterN
    codemirror.js [4883]       window.CodeMirror.BranchChunk.iterN
    codemirror.js [4916]       window.CodeMirror.createObj.iter
    codemirror.js [917]        highlightWorker
    codemirror.js [5603]       anonymous
```

Note that I am running (32-bit) Light Table 0.6.2 (binary version 0.8.4) on Windows 8.1 (x64).
